BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `user` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`fname`	TEXT NOT NULL,
	`lname`	TEXT NOT NULL,
	`email`	TEXT NOT NULL,
	`password`	TEXT NOT NULL
);
COMMIT;
